### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by mauro3** [pwl/ODE.jl#3]
- [x] populate todo-list
- [X] rebase on upstrea/master (@mauro3)
- [ ] add tests which test the rare error-paths
- [X] ode23s
- [x] documentation
- [X] backward time integration for existing solvers
- [ ] benchmark with IVPTS.jl
- [x] refactor to not use `solve` as constructor?
- [ ] check all `TODO` in the code and decide to fix or leave
- [ ] implement `maxiters` option?

Plans post PR-49:
- [ ] root finding
- [ ] wrap Sundials
- [ ] wrap PETSc TS
- [ ] wrap DASSL
- [ ] wrap ODEInterface
- [ ] implement the rest of the solvers in ODE.jl as iterators
- [ ] submethod options
- [ ] per state `isoutofdomain`.
- [ ] optimization (FixedSizeArrays for tableaus?)
- [ ] fix `:points` (do we still want to do that in PR-49?)
- [ ] better status handling and implementation
